#!/usr/bin/env bun

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { jsonStable } from "./core";

const PROJECT_ROOT = resolve(import.meta.dir, "../..");

/** The publishing-only revision used by the TE-00 deterministic layer. */
export const TOKEN_EFFICIENCY_BASELINE_ENGINE_REF =
  "cf128d5e76cc40c0f3d48db0e3873e29d6468e00" as const;
export const TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF = TOKEN_EFFICIENCY_BASELINE_ENGINE_REF;
export const TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF =
  "70cdf3d63ba9dd14ffa6819f32bf3dbc1a632234" as const;
export const TOKEN_EFFICIENCY_REVIEW_BASE_REF =
  "ba84625e189f7ec59838ca8eead355b49791c879" as const;

// Short aliases make the immutable bindings easy to discover without creating
// a second source of truth.
export const TE00_CONTEXT_SOURCE_REVISION = TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF;
export const TE00_REVIEW_CANDIDATE = TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF;
export const TE00_REVIEW_BASE = TOKEN_EFFICIENCY_REVIEW_BASE_REF;

export const TOKEN_EFFICIENCY_QUERIES = {
  focused: "token context bundle review",
  broad: "token context runtime cost efficiency",
  selectedWork: "PV-20",
} as const;

export const TOKEN_EFFICIENCY_ENTRY_PATHS = [
  "AGENTS.md",
  "wiki/index.md",
  "wiki/current-status.md",
  "wiki/product/invariants.md",
] as const;
export const TOKEN_EFFICIENCY_SOURCE_GLOB = "scripts/wiki/**/*.ts" as const;

export const TOKEN_EFFICIENCY_EXPECTED = {
  mandatoryEntryBytes: 16_940,
  focusedContextBytes: 55_046,
  broadContextBytes: 92_758,
  selectedWorkContextBytes: 65_031,
  recursiveTypeScriptBytes: 588_463,
  reviewBundleBytes: 201_631,
  reviewDiffBytes: 138_661,
  reviewNonDiffBytes: 62_970,
} as const;

const DEFAULT_JSON_PATH = join(PROJECT_ROOT, "docs/evidence/te-00-token-efficiency-baseline.json");
const DEFAULT_MARKDOWN_PATH = join(PROJECT_ROOT, "docs/evidence/te-00-token-efficiency-baseline.md");
const DEFAULT_ROLLOUT_PATH = join(PROJECT_ROOT, "docs/evidence/te-00-controlled-rollout.json");

type CommandResult = { exitCode: number; stdout: string; stderr: string };

export type TextMetric = {
  lines: number;
  words: number;
  bytes: number;
};

export type SemanticCounts = {
  pageCount: number;
  currentPageCount: number;
  nonCurrentPageCount: number;
  conflictCount: number;
  sourceDeclarationCount: number;
  sourceFileCount: number;
  readOrderCount: number;
  sourceIds: string[];
  pageIds: string[];
  nonCurrentPageIds: string[];
  conflictIds: string[];
};

export type ContextMeasurement = {
  label: "focused" | "broad" | "selected-work";
  query: string | null;
  workId: string | null;
  text: TextMetric;
  json: TextMetric;
  semantic: SemanticCounts;
};

export type EntryMeasurement = {
  paths: string[];
  files: Record<string, TextMetric>;
  text: TextMetric;
  json: TextMetric;
  semantic: {
    fileCount: number;
    sourcePathCount: number;
    currentAuthorityFileCount: number;
  };
};

export type RecursiveSourceMeasurement = {
  glob: typeof TOKEN_EFFICIENCY_SOURCE_GLOB;
  paths: string[];
  fileCount: number;
  text: TextMetric;
};

export type ReviewBundleFile = {
  path: string;
  bytes: number;
  component: string;
};

export type ReviewBundleMeasurement = {
  candidateRef: typeof TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF;
  baseRef: typeof TOKEN_EFFICIENCY_REVIEW_BASE_REF;
  candidateSha: string;
  baseSha: string;
  metadata: {
    changeType: "feature";
    semanticChange: true;
    wikiAction: "update";
    affectedPages: string[];
    affectedInvariants: string[];
    touchedConflicts: [];
  };
  digest: string;
  files: ReviewBundleFile[];
  fileBytes: Record<string, number>;
  componentBytes: Record<string, number>;
  /** Actual generated bytes, including every serialized manifest field. */
  rawDiffBytes: number;
  rawNonDiffBytes: number;
  /** Proposal-recorded comparison excludes this serialized digest binding. */
  digestBindingBytes: number;
  comparisonDiffBytes: number;
  comparisonNonDiffBytes: number;
  comparisonTotalBytes: number;
  /** Backwards-readable aliases for the raw file accounting. */
  diffBytes: number;
  nonDiffBytes: number;
  totalBytes: number;
  rawTotalBytes: number;
  sourceBreadth: {
    sourceFileCount: number;
    sourcePathCount: number;
    sourcePaths: string[];
    sourceFiles: string[];
    globMatches: Record<string, string[]>;
    affectedPageCount: number;
    invariantCount: number;
    conflictCount: number;
  };
};

export type DeterministicTokenEfficiencyReport = {
  reportVersion: 1;
  contractVersion: 1;
  deterministic: {
    contextSourceRevision: typeof TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF;
    entry: EntryMeasurement;
    focused: ContextMeasurement;
    broad: ContextMeasurement;
    selectedWork: ContextMeasurement;
    recursiveTypeScript: RecursiveSourceMeasurement;
    reviewBundle: ReviewBundleMeasurement;
  };
  summary: {
    mandatoryEntryBytes: number;
    focusedContextBytes: number;
    broadContextBytes: number;
    selectedWorkContextBytes: number;
    recursiveTypeScriptBytes: number;
    reviewBundleBytes: number;
    reviewDiffBytes: number;
    reviewNonDiffBytes: number;
  };
  method: {
    textEncoding: "UTF-8";
    contextCommands: string[];
    sourceExpansion: string;
    reviewBundleCommand: string;
    historicalCheckout: string;
    notes: string[];
  };
};

export type ControlledRolloutAgent = {
  taskLabel: string;
  role: string;
  model: string;
  effort: string;
  modelCallCount: number;
  rawInputTokens: number;
  cachedInputTokens: number;
  uncachedInputTokens: number;
  outputTokens: number;
  reasoningOutputTokens: number;
  totalTokens: number;
};

export type ControlledRolloutTotals = Omit<ControlledRolloutAgent, "taskLabel" | "role" | "model" | "effort"> & {
  agentCount: number;
};

export type ControlledRollout = {
  version: 1;
  kind: "sanitized-controlled-rollout";
  comparison: {
    taskLabel: string;
    contextSourceRevision: string;
    orchestration: string;
  };
  provenance?: {
    kind: "sanitized";
    description: string;
    eventCount?: number;
  };
  agents: ControlledRolloutAgent[];
  totals: ControlledRolloutTotals;
};

export type RolloutValidation = {
  ok: boolean;
  errors: string[];
  rollout?: ControlledRollout;
};

export type TokenEfficiencyEvidence = {
  evidenceVersion: 1;
  deterministic: DeterministicTokenEfficiencyReport;
  controlledRollout: ControlledRollout;
  comparison: {
    exactTask: string;
    contextSourceRevision: string;
    modelAndEffortControls: string[];
    orchestrationControls: string[];
    acceptedVarianceOptions: string[];
    limitations: string[];
  };
  ownerRatification: {
    decision: null;
    options: string[];
  };
};

function run(command: string[], cwd: string, extraEnvironment: Record<string, string> = {}): CommandResult {
  const result = Bun.spawnSync(command, {
    cwd,
    env: { ...process.env, ...extraEnvironment },
    stdout: "pipe",
    stderr: "pipe",
  });
  return { exitCode: result.exitCode, stdout: result.stdout.toString(), stderr: result.stderr.toString() };
}

function required(command: string[], cwd: string, extraEnvironment: Record<string, string> = {}): CommandResult {
  const result = run(command, cwd, extraEnvironment);
  if (result.exitCode !== 0) throw new Error(`${command.join(" ")} failed\n${result.stderr || result.stdout}`);
  return result;
}

function git(root: string, args: string[], allowFailure = false): string {
  return required(["git", ...args], root, allowFailure ? {} : {}).stdout.trim();
}

function metric(text: string): TextMetric {
  const trimmed = text.trim();
  return {
    lines: (text.match(/\n/g) ?? []).length,
    words: trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length,
    bytes: Buffer.byteLength(text, "utf8"),
  };
}

function sumMetrics(metrics: TextMetric[]): TextMetric {
  return metrics.reduce((sum, item) => ({
    lines: sum.lines + item.lines,
    words: sum.words + item.words,
    bytes: sum.bytes + item.bytes,
  }), { lines: 0, words: 0, bytes: 0 });
}

function sortedPaths(root: string, relativeRoot: string, suffix?: string): string[] {
  const absolute = join(root, relativeRoot);
  if (!existsSync(absolute)) return [];
  const output: string[] = [];
  const visit = (path: string) => {
    for (const entry of readdirSync(path, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const child = join(path, entry.name);
      if (entry.isDirectory()) visit(child);
      else if (!suffix || child.endsWith(suffix)) output.push(relative(root, child).replaceAll("\\", "/"));
    }
  };
  if (statSync(absolute).isDirectory()) visit(absolute);
  else if (!suffix || absolute.endsWith(suffix)) output.push(relative(root, absolute).replaceAll("\\", "/"));
  return output.sort((a, b) => a.localeCompare(b));
}

function summarizeContext(value: unknown): SemanticCounts {
  const object = value as Record<string, unknown>;
  const pages = Array.isArray(object.pages) ? object.pages as Record<string, unknown>[] : [];
  const nonCurrent = Array.isArray(object.nonCurrentPages) ? object.nonCurrentPages as Record<string, unknown>[] : [];
  const conflicts = Array.isArray(object.conflicts) ? object.conflicts as Record<string, unknown>[] : [];
  const sources = Array.isArray(object.sources) ? object.sources as Record<string, unknown>[] : [];
  const sourceFiles = new Set<string>();
  const sourceIds = sources.flatMap((item) => typeof item.pageId === "string" ? [item.pageId] : []);
  const sourceDeclarationCount = sources.reduce((count, item) => count + (Array.isArray(item.declared) ? item.declared.length : 0), 0);
  for (const source of [...pages, ...nonCurrent, ...sources]) {
    for (const path of Array.isArray(source.sourceFiles) ? source.sourceFiles : []) if (typeof path === "string") sourceFiles.add(path);
  }
  return {
    pageCount: pages.length,
    currentPageCount: pages.filter((page) => page.status === "current").length,
    nonCurrentPageCount: nonCurrent.length,
    conflictCount: conflicts.length,
    sourceDeclarationCount,
    sourceFileCount: sourceFiles.size,
    readOrderCount: Array.isArray(object.readOrder) ? object.readOrder.length : 0,
    sourceIds: [...new Set(sourceIds)].sort((a, b) => a.localeCompare(b)),
    pageIds: pages.flatMap((page) => typeof page.id === "string" ? [page.id] : []).sort((a, b) => a.localeCompare(b)),
    nonCurrentPageIds: nonCurrent.flatMap((page) => typeof page.id === "string" ? [page.id] : []).sort((a, b) => a.localeCompare(b)),
    conflictIds: conflicts.flatMap((conflict) => typeof conflict.id === "string" ? [conflict.id] : []).sort((a, b) => a.localeCompare(b)),
  };
}

function cli(root: string, args: string[]): CommandResult {
  return run([process.execPath, join(root, "scripts/wiki/cli.ts"), ...args], root);
}

function requiredCli(root: string, args: string[]): CommandResult {
  const result = cli(root, args);
  if (result.exitCode !== 0) throw new Error(`wiki ${args.join(" ")} failed\n${result.stderr || result.stdout}`);
  return result;
}

function entryMeasurement(root: string): EntryMeasurement {
  const files = Object.fromEntries(TOKEN_EFFICIENCY_ENTRY_PATHS.map((path) => [path, metric(readFileSync(join(root, path), "utf8"))]));
  const text = sumMetrics(Object.values(files));
  const json = metric(jsonStable({ paths: [...TOKEN_EFFICIENCY_ENTRY_PATHS], files }));
  return {
    paths: [...TOKEN_EFFICIENCY_ENTRY_PATHS],
    files,
    text,
    json,
    semantic: { fileCount: 4, sourcePathCount: 4, currentAuthorityFileCount: 1 },
  };
}

function contextMeasurement(root: string, label: ContextMeasurement["label"], query: string | null, workId: string | null): ContextMeasurement {
  const args = workId == null ? ["context", query!, "--json"] : ["context", "--work", workId, "--json"];
  const jsonResult = requiredCli(root, args);
  const value = JSON.parse(jsonResult.stdout) as unknown;
  const textResult = workId == null
    ? requiredCli(root, ["context", query!])
    : requiredCli(root, ["context", "--work", workId]);
  return { label, query, workId, text: metric(textResult.stdout), json: metric(jsonResult.stdout), semantic: summarizeContext(value) };
}

function recursiveSourceMeasurement(root: string): RecursiveSourceMeasurement {
  // The runner is publishing-only evidence and did not exist at the pinned
  // context revision. Exclude its copied historical launcher from the source
  // boundary so the reproduction remains the exact 22-file expansion.
  const paths = sortedPaths(root, "scripts/wiki", ".ts")
    .filter((path) => path !== "scripts/wiki/token-efficiency-baseline.ts");
  const files = paths.map((path) => metric(readFileSync(join(root, path), "utf8")));
  return { glob: TOKEN_EFFICIENCY_SOURCE_GLOB, paths, fileCount: paths.length, text: sumMetrics(files) };
}

function canonicalMetadataRaw(): string {
  return [
    "```yaml",
    "change_type: feature",
    "semantic_change: true",
    "wiki_action: update",
    "affected_pages:",
    "  - architecture/engine",
    "  - operations/enforcement",
    "  - product/invariants",
    "  - product/scope",
    "affected_invariants:",
    "  - product/invariants",
    "touched_conflicts: []",
    "fresh_context:",
    "  verdict: PENDING",
    "  reviewed_head_sha: \"\"",
    "  bundle_digest: \"\"",
    "  reviewer: \"\"",
    "  evidence: []",
    "```",
    "",
  ].join("\n");
}

function componentFor(path: string): string {
  if (path === "diff.patch") return "diff";
  if (path.startsWith("pages/")) return "pages";
  if (path.startsWith("invariants/")) return "invariants";
  if (path.startsWith("conflicts/")) return "conflicts";
  if (path === "manifest.json") return "manifest";
  if (path === "impact.json") return "impact";
  if (path === "pr-metadata.json") return "metadata";
  if (path === "sources.json") return "sources";
  return "review-contract";
}

function reviewBundleMeasurement(root: string): ReviewBundleMeasurement {
  const temporaryRoot = mkdtempSync(join(tmpdir(), "wiki-ssot-te00-bundle-"));
  const candidateRoot = join(temporaryRoot, "candidate");
  const metadataPath = join(temporaryRoot, "metadata.md");
  const outputPath = join(temporaryRoot, "bundle");
  try {
    required(["git", "clone", "--quiet", "--shared", "--no-checkout", root, candidateRoot], root);
    required(["git", "checkout", "--quiet", "--detach", TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF], candidateRoot);
    const candidateSha = git(candidateRoot, ["rev-parse", "HEAD"]);
    const baseSha = git(candidateRoot, ["rev-parse", TOKEN_EFFICIENCY_REVIEW_BASE_REF + "^{commit}"]);
    if (candidateSha !== TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF || baseSha !== TOKEN_EFFICIENCY_REVIEW_BASE_REF) {
      throw new Error("TE-00 review refs did not resolve to their immutable commits");
    }
    const nodeModules = join(root, "node_modules");
    if (existsSync(nodeModules)) symlinkSync(nodeModules, join(candidateRoot, "node_modules"), "dir");
    writeFileSync(metadataPath, canonicalMetadataRaw(), "utf8");
    const result = requiredCli(candidateRoot, [
      "review-bundle",
      "--base",
      TOKEN_EFFICIENCY_REVIEW_BASE_REF,
      "--metadata",
      metadataPath,
      "--output",
      outputPath,
      "--json",
    ]);
    const parsed = JSON.parse(result.stdout) as { manifest?: { bundle_digest?: string } };
    const paths = sortedPaths(outputPath, "");
    const rawFileBytes = Object.fromEntries(paths.map((path) => [path, Buffer.byteLength(readFileSync(join(outputPath, path)), "utf8")]));
    const rawTotalBytes = Object.values(rawFileBytes).reduce((sum, bytes) => sum + bytes, 0);
    const fileBytes = { ...rawFileBytes };
    const files = paths.map((path) => ({ path, bytes: fileBytes[path], component: componentFor(path) }));
    const componentBytes: Record<string, number> = {};
    for (const file of files) componentBytes[file.component] = (componentBytes[file.component] ?? 0) + file.bytes;
    const rawDiffBytes = fileBytes["diff.patch"] ?? 0;
    const rawNonDiffBytes = rawTotalBytes - rawDiffBytes;
    const digestBindingBytes = 70;
    const comparisonDiffBytes = rawDiffBytes;
    const comparisonTotalBytes = rawTotalBytes - digestBindingBytes;
    const comparisonNonDiffBytes = comparisonTotalBytes - comparisonDiffBytes;
    const manifestDigest = parsed.manifest?.bundle_digest;
    if (typeof manifestDigest !== "string" || manifestDigest.length === 0) throw new Error("TE-00 review bundle did not return a bundle digest");
    const sourceJson = JSON.parse(readFileSync(join(outputPath, "sources.json"), "utf8")) as Record<string, unknown>;
    const affectedPages = ["architecture/engine", "operations/enforcement", "product/invariants", "product/scope"];
    const invariantIds = ["product/invariants"];
    const sourcePathSet = new Set<string>();
    const globSet = new Set<string>();
    for (const value of Object.values((sourceJson.affectedPages ?? {}) as Record<string, unknown>)) {
      for (const source of Array.isArray(value) ? value : []) {
        if (source == null || typeof source !== "object" || Array.isArray(source)) continue;
        const declaration = source as Record<string, unknown>;
        if (typeof declaration.path === "string") sourcePathSet.add(declaration.path);
        if (typeof declaration.glob === "string") globSet.add(declaration.glob);
      }
    }
    const candidateTree = git(candidateRoot, ["ls-tree", "-r", "--name-only", TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF])
      .split("\n").filter(Boolean).sort((a, b) => a.localeCompare(b));
    const globMatches: Record<string, string[]> = {};
    const sourceFileSet = new Set(sourcePathSet);
    for (const pattern of [...globSet].sort((a, b) => a.localeCompare(b))) {
      let glob: Bun.Glob;
      try {
        glob = new Bun.Glob(pattern);
      } catch {
        throw new Error(`TE-00 review source glob is invalid: ${pattern}`);
      }
      const matches = candidateTree.filter((path) => glob.match(path)).sort((a, b) => a.localeCompare(b));
      globMatches[pattern] = matches;
      for (const path of matches) sourceFileSet.add(path);
    }
    const sourcePaths = [...sourcePathSet].sort((a, b) => a.localeCompare(b));
    const sourceFiles = [...sourceFileSet].sort((a, b) => a.localeCompare(b));
    return {
      candidateRef: TOKEN_EFFICIENCY_REVIEW_CANDIDATE_REF,
      baseRef: TOKEN_EFFICIENCY_REVIEW_BASE_REF,
      candidateSha,
      baseSha,
      metadata: {
        changeType: "feature",
        semanticChange: true,
        wikiAction: "update",
        affectedPages,
        affectedInvariants: invariantIds,
        touchedConflicts: [],
      },
      digest: manifestDigest,
      files,
      fileBytes,
      componentBytes,
      rawDiffBytes,
      rawNonDiffBytes,
      digestBindingBytes,
      comparisonDiffBytes,
      comparisonNonDiffBytes,
      comparisonTotalBytes,
      diffBytes: rawDiffBytes,
      nonDiffBytes: rawNonDiffBytes,
      totalBytes: rawTotalBytes,
      rawTotalBytes,
      sourceBreadth: {
        sourceFileCount: sourceFiles.length,
        sourcePathCount: sourcePaths.length,
        sourcePaths,
        sourceFiles,
        globMatches,
        affectedPageCount: affectedPages.length,
        invariantCount: invariantIds.length,
        conflictCount: 0,
      },
    };
  } finally {
    rmSync(temporaryRoot, { recursive: true, force: true });
  }
}

function buildAtRoot(root: string): DeterministicTokenEfficiencyReport {
  const baseSha = git(root, ["rev-parse", TOKEN_EFFICIENCY_BASELINE_ENGINE_REF + "^{commit}"]);
  const head = git(root, ["rev-parse", "HEAD"]);
  if (process.env.WIKI_TE00_PINNED_ROOT === TOKEN_EFFICIENCY_BASELINE_ENGINE_REF && head !== TOKEN_EFFICIENCY_BASELINE_ENGINE_REF) {
    throw new Error("TE-00 pinned runner did not receive the immutable context/source checkout");
  }
  const entry = entryMeasurement(root);
  const focused = contextMeasurement(root, "focused", TOKEN_EFFICIENCY_QUERIES.focused, null);
  const broad = contextMeasurement(root, "broad", TOKEN_EFFICIENCY_QUERIES.broad, null);
  const selectedWork = contextMeasurement(root, "selected-work", null, TOKEN_EFFICIENCY_QUERIES.selectedWork);
  const recursiveTypeScript = recursiveSourceMeasurement(root);
  const reviewBundle = reviewBundleMeasurement(root);
  return {
    reportVersion: 1,
    contractVersion: 1,
    deterministic: {
      contextSourceRevision: TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF,
      entry,
      focused,
      broad,
      selectedWork,
      recursiveTypeScript,
      reviewBundle,
    },
    summary: {
      mandatoryEntryBytes: entry.text.bytes,
      focusedContextBytes: focused.text.bytes,
      broadContextBytes: broad.text.bytes,
      selectedWorkContextBytes: selectedWork.text.bytes,
      recursiveTypeScriptBytes: recursiveTypeScript.text.bytes,
      reviewBundleBytes: reviewBundle.comparisonTotalBytes,
      reviewDiffBytes: reviewBundle.comparisonDiffBytes,
      reviewNonDiffBytes: reviewBundle.comparisonNonDiffBytes,
    },
    method: {
      textEncoding: "UTF-8",
      contextCommands: [
        "bun run wiki:context -- \"" + TOKEN_EFFICIENCY_QUERIES.focused + "\"",
        "bun run wiki:context -- \"" + TOKEN_EFFICIENCY_QUERIES.broad + "\"",
        "bun run wiki:context -- --work " + TOKEN_EFFICIENCY_QUERIES.selectedWork,
      ],
      sourceExpansion: TOKEN_EFFICIENCY_SOURCE_GLOB,
      reviewBundleCommand: `bun run wiki:review-bundle -- --base ${TOKEN_EFFICIENCY_REVIEW_BASE_REF}`,
      historicalCheckout: `git clone --shared --no-checkout; git checkout --detach ${TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF}`,
      notes: [
        "All deterministic measurements are UTF-8 bytes and are not model-token, runtime, billing, or subscription-credit claims.",
        "The context/source and review candidate checkouts are detached immutable revisions; moving refs cannot rewrite this evidence.",
        "Review bundle file/component totals retain every generated byte (201,701); the proposal-recorded comparison explicitly excludes a 70-byte serialized bundle_digest binding, yielding 201,631 bytes.",
      ],
    },
  };
}

function buildHistoricalReport(): DeterministicTokenEfficiencyReport {
  const temporaryRoot = mkdtempSync(join(tmpdir(), "wiki-ssot-te00-engine-"));
  const checkoutRoot = join(temporaryRoot, "repo");
  const outputPath = join(temporaryRoot, "report.json");
  try {
    required(["git", "clone", "--quiet", "--shared", "--no-checkout", PROJECT_ROOT, checkoutRoot], PROJECT_ROOT);
    required(["git", "checkout", "--quiet", "--detach", TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF], checkoutRoot);
    const source = join(import.meta.dir, "token-efficiency-baseline.ts");
    mkdirSync(dirname(join(checkoutRoot, "scripts/wiki/token-efficiency-baseline.ts")), { recursive: true });
    writeFileSync(join(checkoutRoot, "scripts/wiki/token-efficiency-baseline.ts"), readFileSync(source, "utf8"), "utf8");
    // Keep the copied launcher outside the historical repository view. The
    // source glob and CLI both use Git's tracked/untracked file boundary.
    writeFileSync(join(checkoutRoot, ".git/info/exclude"), "\nscripts/wiki/token-efficiency-baseline.ts\n", { flag: "a" });
    const nodeModules = join(PROJECT_ROOT, "node_modules");
    if (existsSync(nodeModules)) symlinkSync(nodeModules, join(checkoutRoot, "node_modules"), "dir");
    required([
      process.execPath,
      join(checkoutRoot, "scripts/wiki/token-efficiency-baseline.ts"),
      "--internal-output",
      outputPath,
    ], checkoutRoot, { WIKI_TE00_PINNED_ROOT: TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF });
    const report = JSON.parse(readFileSync(outputPath, "utf8")) as DeterministicTokenEfficiencyReport;
    if (report.deterministic.contextSourceRevision !== TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF) throw new Error("TE-00 historical report has the wrong source revision");
    return report;
  } finally {
    rmSync(temporaryRoot, { recursive: true, force: true });
  }
}

export function buildTokenEfficiencyBaselineReport(): DeterministicTokenEfficiencyReport {
  const head = git(PROJECT_ROOT, ["rev-parse", "HEAD"]);
  return head === TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF || process.env.WIKI_TE00_PINNED_ROOT === TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF
    ? buildAtRoot(PROJECT_ROOT)
    : buildHistoricalReport();
}

// Naming aliases keep the publishing evidence API explicit while allowing
// callers to use either the long report name or the TE-00 shorthand.
export const buildTokenEfficiencyReport = buildTokenEfficiencyBaselineReport;
export const buildTE00BaselineReport = buildTokenEfficiencyBaselineReport;

function isFiniteNonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && Number.isInteger(value) && value >= 0;
}

function forbiddenRolloutKey(key: string): boolean {
  return /(transcript|prompt|private.?path|session.?path|thread.?id|session.?id|absolute.?path|file.?path|working.?directory)/i.test(key);
}

function scanForbiddenValues(value: unknown, path = "rollout"): string[] {
  if (Array.isArray(value)) return value.flatMap((item, index) => scanForbiddenValues(item, `${path}[${index}]`));
  if (value == null || typeof value !== "object") return [];
  const errors: string[] = [];
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    if (forbiddenRolloutKey(key)) errors.push(`${path}.${key} is not permitted in sanitized rollout input`);
    errors.push(...scanForbiddenValues(child, `${path}.${key}`));
  }
  return errors;
}

// Accept the two common neutral spellings used by local usage exporters while
// emitting one canonical, versioned shape. The aliases carry no additional
// information and are normalized before accounting is checked.
const TOKEN_FIELD_ALIASES: Record<string, string[]> = {
  rawInputTokens: ["rawInputTokens", "inputTokens", "rawInput"],
  cachedInputTokens: ["cachedInputTokens", "cachedInput"],
  uncachedInputTokens: ["uncachedInputTokens", "derivedUncachedInputTokens", "uncachedInput"],
  outputTokens: ["outputTokens", "output"],
  reasoningOutputTokens: ["reasoningOutputTokens", "reasoningOutput"],
  totalTokens: ["totalTokens", "total"],
};

function normalizeTokenFields(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeTokenFields);
  if (value == null || typeof value !== "object") return value;
  const object = value as Record<string, unknown>;
  const normalized: Record<string, unknown> = { ...object };
  for (const [canonical, aliases] of Object.entries(TOKEN_FIELD_ALIASES)) {
    if (normalized[canonical] !== undefined) continue;
    const alias = aliases.find((key) => normalized[key] !== undefined);
    if (alias != null) normalized[canonical] = normalized[alias];
  }
  if (Array.isArray(normalized.agents)) normalized.agents = normalized.agents.map(normalizeTokenFields);
  if (normalized.totals != null) normalized.totals = normalizeTokenFields(normalized.totals);
  return normalized;
}

function rolloutAgent(value: unknown, index: number, errors: string[]): ControlledRolloutAgent | undefined {
  if (value == null || typeof value !== "object" || Array.isArray(value)) {
    errors.push(`agents[${index}] must be an object`);
    return undefined;
  }
  const item = value as Record<string, unknown>;
  const strings = ["taskLabel", "role", "model", "effort"];
  for (const key of strings) if (typeof item[key] !== "string" || String(item[key]).trim().length === 0) errors.push(`agents[${index}].${key} must be a non-empty string`);
  const numbers = ["modelCallCount", "rawInputTokens", "cachedInputTokens", "uncachedInputTokens", "outputTokens", "reasoningOutputTokens", "totalTokens"] as const;
  for (const key of numbers) if (!isFiniteNonNegativeInteger(item[key])) errors.push(`agents[${index}].${key} must be a finite non-negative integer`);
  if (errors.some((error) => error.startsWith(`agents[${index}]`))) return undefined;
  const agent = item as unknown as ControlledRolloutAgent;
  if (agent.modelCallCount < 1) errors.push(`agents[${index}].modelCallCount must be at least one`);
  if (agent.cachedInputTokens > agent.rawInputTokens) errors.push(`agents[${index}].cachedInputTokens cannot exceed rawInputTokens`);
  if (agent.uncachedInputTokens !== agent.rawInputTokens - agent.cachedInputTokens) errors.push(`agents[${index}].uncachedInputTokens must equal rawInputTokens - cachedInputTokens`);
  if (agent.reasoningOutputTokens > agent.outputTokens) errors.push(`agents[${index}].reasoningOutputTokens cannot exceed outputTokens`);
  if (agent.totalTokens !== agent.rawInputTokens + agent.outputTokens) errors.push(`agents[${index}].totalTokens must equal rawInputTokens + outputTokens`);
  return { ...agent };
}

function aggregateAgents(agents: ControlledRolloutAgent[]): ControlledRolloutTotals {
  return {
    agentCount: agents.length,
    modelCallCount: agents.reduce((sum, item) => sum + item.modelCallCount, 0),
    rawInputTokens: agents.reduce((sum, item) => sum + item.rawInputTokens, 0),
    cachedInputTokens: agents.reduce((sum, item) => sum + item.cachedInputTokens, 0),
    uncachedInputTokens: agents.reduce((sum, item) => sum + item.uncachedInputTokens, 0),
    outputTokens: agents.reduce((sum, item) => sum + item.outputTokens, 0),
    reasoningOutputTokens: agents.reduce((sum, item) => sum + item.reasoningOutputTokens, 0),
    totalTokens: agents.reduce((sum, item) => sum + item.totalTokens, 0),
  };
}

export function inspectControlledRollout(input: unknown): RolloutValidation {
  const errors = scanForbiddenValues(input);
  if (input == null || typeof input !== "object" || Array.isArray(input)) return { ok: false, errors: [...errors, "rollout must be an object"] };
  const value = normalizeTokenFields(input) as Record<string, unknown>;
  if (value.version !== 1) errors.push("rollout.version must be 1");
  if (value.kind !== "sanitized-controlled-rollout") errors.push("rollout.kind must be sanitized-controlled-rollout");
  const comparison = value.comparison;
  if (comparison == null || typeof comparison !== "object" || Array.isArray(comparison)) errors.push("rollout.comparison must be an object");
  else {
    for (const key of ["taskLabel", "contextSourceRevision", "orchestration"]) if (typeof (comparison as Record<string, unknown>)[key] !== "string" || String((comparison as Record<string, unknown>)[key]).trim().length === 0) errors.push(`rollout.comparison.${key} must be a non-empty string`);
  }
  if (value.provenance != null && (typeof value.provenance !== "object" || Array.isArray(value.provenance))) errors.push("rollout.provenance must be an object");
  const rawAgents = value.agents;
  if (!Array.isArray(rawAgents) || rawAgents.length === 0) errors.push("rollout.agents must be a non-empty array");
  const agents = Array.isArray(rawAgents) ? rawAgents.flatMap((item, index) => { const agent = rolloutAgent(item, index, errors); return agent ? [agent] : []; }) : [];
  const expectedTotals = aggregateAgents(agents);
  const totals = value.totals;
  if (totals == null || typeof totals !== "object" || Array.isArray(totals)) errors.push("rollout.totals must be an object");
  else {
    const suppliedTotals = totals as Record<string, unknown>;
    for (const key of Object.keys(expectedTotals) as (keyof ControlledRolloutTotals)[]) if (suppliedTotals[key] !== expectedTotals[key]) errors.push(`rollout.totals.${key} must equal the aggregate of agents`);
  }
  if (errors.length > 0) return { ok: false, errors };
  return { ok: true, errors: [], rollout: {
    version: 1,
    kind: "sanitized-controlled-rollout",
    comparison: comparison as ControlledRollout["comparison"],
    ...(value.provenance == null ? {} : { provenance: value.provenance as ControlledRollout["provenance"] }),
    agents,
    totals: expectedTotals,
  } };
}

export function validateControlledRollout(input: unknown): ControlledRollout {
  const result = inspectControlledRollout(input);
  if (!result.ok || result.rollout == null) throw new Error(`invalid controlled rollout:\n${result.errors.join("\n")}`);
  return result.rollout;
}

export const validateTE00ControlledRollout = validateControlledRollout;

export function buildTokenEfficiencyEvidence(
  report: DeterministicTokenEfficiencyReport,
  rolloutInput: unknown,
): TokenEfficiencyEvidence {
  const controlledRollout = validateControlledRollout(rolloutInput);
  return {
    evidenceVersion: 1,
    deterministic: report,
    controlledRollout,
    comparison: {
      exactTask: "Measure the real repository's mandatory entry, focused and broad topic context, PV-20 selected-work context, recursive TypeScript source expansion, and the 70cdf3d candidate review bundle against the pinned revisions.",
      contextSourceRevision: TOKEN_EFFICIENCY_CONTEXT_SOURCE_REF,
      modelAndEffortControls: ["Record the exact model and reasoning effort per rollout agent; do not compare different model or effort settings without a declared variance."],
      orchestrationControls: ["Keep agent role, model-call count, and fan-out/orchestration policy fixed for comparison; deterministic repository measurements remain separate from rollout usage."],
      acceptedVarianceOptions: ["Owner may accept a documented model, cache, orchestration, or sampling variance when the exact task and controls are preserved."],
      limitations: ["UTF-8 bytes and local token counts are evidence, not runtime, billed API cost, subscription credits, or proof of model comprehension."],
    },
    ownerRatification: {
      decision: null,
      options: ["ratify targets", "request another bounded measurement cycle", "do not adopt optimization"],
    },
  };
}

export const buildCombinedTokenEfficiencyEvidence = buildTokenEfficiencyEvidence;
export const buildTokenEfficiencyBaselineEvidence = buildTokenEfficiencyEvidence;

export function renderTokenEfficiencyEvidenceJson(evidence: TokenEfficiencyEvidence): string {
  return jsonStable(evidence);
}

export function renderTokenEfficiencyOwnerRatification(evidence: TokenEfficiencyEvidence): string {
  const deterministic = evidence.deterministic.summary;
  const rollout = evidence.controlledRollout.totals;
  return [
    "# TE-00 token-efficiency baseline",
    "",
    `Deterministic evidence is pinned to context/source revision \`${evidence.deterministic.deterministic.contextSourceRevision}\` and measured as UTF-8 bytes. It is separate from controlled model rollout usage and does not claim runtime or billed cost.`,
    "",
    "## Correctness floor and proposed targets",
    "",
    "- PV-19 correctness floor: preserve every current-page, invariant, conflict, implementation-source, authority-label, non-current-label, expected-change, Wiki-action, coverage, and drift-gate expectation.",
    "- Proposed context target: at most 40% of the reproduced deterministic context baseline.",
    "- Proposed uncached-input target: at most 60% of the controlled end-to-end baseline.",
    "",
    "## Exact comparison task",
    "",
    `- Compare the pinned real-repository cases and review candidate named by the machine-readable report at \`${evidence.deterministic.deterministic.contextSourceRevision}\`.`,
    `- Deterministic bytes: entry ${deterministic.mandatoryEntryBytes}; focused ${deterministic.focusedContextBytes}; broad ${deterministic.broadContextBytes}; selected work ${deterministic.selectedWorkContextBytes}; recursive TypeScript ${deterministic.recursiveTypeScriptBytes}; review bundle ${deterministic.reviewBundleBytes}.`,
    "",
    "## Controlled rollout controls",
    "",
    `- Agent/model/effort records: ${rollout.agentCount} agent(s), ${rollout.modelCallCount} model calls, ${rollout.rawInputTokens} raw input tokens (${rollout.cachedInputTokens} cached, ${rollout.uncachedInputTokens} derived uncached), ${rollout.outputTokens} output tokens (${rollout.reasoningOutputTokens} reasoning subset), ${rollout.totalTokens} total.`,
    "- Keep task label, role, model, effort, call count, and orchestration fixed; cached input is already included in raw input and reasoning output is already included in output.",
    "",
    "## Variance and limitations",
    "",
    "- Accepted variance options must be recorded by the owner: model/cache behavior, orchestration fan-out, or bounded sampling variance.",
    "- The rollout is sanitized: no transcript, prompt, private path, session identifier, or thread identifier is retained.",
    "- Local token counts are not billed cost or subscription-credit claims, and deterministic bytes do not establish model comprehension.",
    "",
    "## Owner ratification",
    "",
    "Decision: **unselected**",
    "",
    "Choose one: ratify targets; request another bounded measurement cycle; or do not adopt the optimization.",
    "",
  ].join("\n");
}

export const renderTokenEfficiencyBaselineMarkdown = renderTokenEfficiencyOwnerRatification;
export const renderTokenEfficiencyInterpretation = renderTokenEfficiencyOwnerRatification;
export const renderTokenEfficiencyMarkdown = renderTokenEfficiencyOwnerRatification;

function parseFlag(flag: string, fallback: string): string {
  const index = process.argv.indexOf(flag);
  if (index === -1) return fallback;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`${flag} requires a path`);
  return resolve(PROJECT_ROOT, value);
}

if (import.meta.main) {
  const internalOutputIndex = process.argv.indexOf("--internal-output");
  if (internalOutputIndex !== -1) {
    const path = process.argv[internalOutputIndex + 1];
    if (!path) throw new Error("--internal-output requires a path");
    writeFileSync(path, jsonStable(buildAtRoot(PROJECT_ROOT)), "utf8");
  } else {
    const report = buildTokenEfficiencyBaselineReport();
    const rolloutPath = parseFlag("--rollout", DEFAULT_ROLLOUT_PATH);
    if (!existsSync(rolloutPath)) throw new Error(`controlled rollout input is missing: ${rolloutPath}`);
    const evidence = buildTokenEfficiencyEvidence(report, JSON.parse(readFileSync(rolloutPath, "utf8")));
    const jsonPath = parseFlag("--output", DEFAULT_JSON_PATH);
    const markdownPath = parseFlag("--interpretation", parseFlag("--markdown", DEFAULT_MARKDOWN_PATH));
    const jsonText = renderTokenEfficiencyEvidenceJson(evidence);
    const markdownText = renderTokenEfficiencyOwnerRatification(evidence);
    if (process.argv.includes("--check")) {
      const mismatches = [[jsonPath, jsonText], [markdownPath, markdownText]].filter(([path, expected]) => {
        try { return readFileSync(path, "utf8") !== expected; } catch { return true; }
      });
      if (mismatches.length > 0) throw new Error(`TE-00 evidence is stale: ${mismatches.map(([path]) => path).join(", ")}`);
      console.log("TE-00 token-efficiency evidence is current");
    } else {
      mkdirSync(dirname(jsonPath), { recursive: true });
      mkdirSync(dirname(markdownPath), { recursive: true });
      writeFileSync(jsonPath, jsonText, "utf8");
      writeFileSync(markdownPath, markdownText, "utf8");
      console.log(`wrote ${jsonPath}`);
      console.log(`wrote ${markdownPath}`);
    }
  }
}
